### ISSUE TITLE
Problem of rounding off figures in stock

### ISSUE THREAD

**Issue by Samipouet** [msupply-foundation/open-msupply#6941]
## NOTE:

**This has been re-opened, for ongoing discussion of decimal quantities that don't round nicely. Please see below comments.**

## What went wrong? 😲

There is a decimal problem in the stock display.  
The first screen shoot shows a quantity of 6.800000000000001.

![Image](https://github.com/user-attachments/assets/5861f95f-0b09-4bcf-9f0a-0fd8a50fac2f)

The second shows a quantity of 19.099999999999994.

<img width="1234" alt="Image" src="https://github.com/user-attachments/assets/d66b0202-5e4d-4a10-83bc-c245d4f6f5e9" />

I think this happens after a dose of vaccine is delivered in the dispensary (but not for all vaccines and after every dispensation).

## Expected behaviour 🤔

Rounding must be to the second decimal place.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Dispense a new dose in Dispensary. (choose a Patient, add an encounter in the past, save and click on one vaccine to dispense, Dispense it)
2.  Go to 'Inventory', 'View Stock' 
3. The error is not found for all vaccines and for all dispensations. 

## Your environment 🌱

- Open mSupply Version: 2.6.00 Demo
- Legacy mSupply Central Server Version: N/A

- Platform: Mac 

- Database type: 

@richardmoizeau

**Comment by jmbrunskill** [comment]
Maybe for 2.7 don't think we need to hotfix?

**Comment by richardmoizeau** [comment]
Hi James, we need it fixed by mid-april for the next Djibouti trip. Would that work ?

**Comment by aimee-mcneil-melville** [comment]
I'm adding on to this that the this rounding is also present in the adjustments (I've just added adjusting by decimal places now).

I also could only replicate in vaccine items. The example here was a brand new vaccine item - second transaction in ledger is the result of submitting adjustment of 0.36 at the end of the recording 

![Image](https://github.com/user-attachments/assets/88ad7169-1e55-4a48-86ba-d5370be33656)

https://github.com/user-attachments/assets/cd0a0dae-81d0-416e-a327-7f42fa0d1b52

**Comment by CarlosNZ** [comment]
Closed by #7216

**Comment by Samipouet** [comment]
Hello, during deployment we notice the issue is still there :(

<img width="591" alt="Image" src="https://github.com/user-attachments/assets/f4265273-1c7e-4af5-b0f9-3501e2b12535" />

**Comment by zachariah-at-msupply** [comment]
Oh no!!! Investigating ASAP. I hope all is going well for you guys despite this!

**Comment by zachariah-at-msupply** [comment]
Hello, I believe I see a way to fix for this, but just checking how I should prioritise the issue - is it a hotfix or maybe something for later? @jmbrunskill @roxy-dao

**Comment by mark-prins** [comment]
not a hotfix - it isn't stopping anyone working

**Comment by zachariah-at-msupply** [comment]
The problem seems to be that, when we have pack values more than 2d.p, rounding is applied in the cell but not in the tooltip. I've updated the relevant component in the code (.../Cells/NumberInputCell/NumberCell.tsx) so that the tooltip is the same as the cell's value :) 

The PR is here: https://github.com/msupply-foundation/open-msupply/pull/7688

**Comment by richardmoizeau** [comment]
> not a hotfix - it isn't stopping anyone working

I'll let @Samipouet have the final say but I think this issue was quite annoying, especially for vaccination units to identify open vial wastage.

**Comment by zachariah-at-msupply** [comment]
Requires further investigation and we are prioritising 2.8.0 work atm, so will unassign myself.
It seem there are are two issues at play:
1. Wierd numbers need to display properly (believe fixed in original PR)
2. How are wierd numbers being generated anyway (requires investigation)
Unsure whether to make a new issue for the second one as it seems to be relevant to this one.

**Comment by Samipouet** [comment]
Yes it's really confusing for the users, they don't understand what it means.
Plus they noticed it 2 months ago, and we told them it was going to be fixed for the deployment.

**Comment by Samipouet** [comment]
(sorry I closed the issue accidentally)

**Comment by andreievg** [comment]
Would suggest setting 2dp rounding for all number inputs by default (when non editable)

**Comment by jmbrunskill** [comment]
@mark-prins can you clarify which solution we want from @roxy-dao 's message above?

**Comment by mark-prins** [comment]
option 1 thanks. round to 2dp and show an ellipsis to indicate that the rounding has happened and that there is a tooltip available

**Comment by aimee-mcneil-melville** [comment]
@mark-prins can you please confirm in regards to the tooltips formatting:

1. Should the NumberCell tooltip be rounded to a particular length? I know there are some requirements to show 10dp, however these are currently uncapped and I've seen up to 16dp

Proposing to round the tooltip on number cells to 10dp, which IMO also improves the readability when it comes to precision numbers

Unrounded tooltip:
<img width="181" height="96" alt="Image" src="https://github.com/user-attachments/assets/3ae1a26f-4878-4770-ad9c-6ed4c7f6245e" />

Rounded tooltip:
<img width="181" height="96" alt="Image" src="https://github.com/user-attachments/assets/9c7967ab-861b-4d9f-bfbe-265e33b925a8" />

2. Currency Cell: Currently this is set up to have the ellipsis and tooltip, however when the tooltip goes through currency formatting it also trims the cents to 2dp (even though precision 10 is passed in at the CurrencyCell level). Should currency have:
      a. No tooltip, display just the regional currency format in the cell
      b. Tooltip to 10dp without currency formatting eg 3.2222222222
      c. Tooltip to 10dp with regional currency formatting eg $3.2222222222

**Comment by aimee-mcneil-melville** [comment]
There's also places that use NumericTextInputs instead of Cells. these have no default tooltip behaviour - should these also have a similar implementation?

This is the Inventory Adjustment Modal - the `2.93` values in this example read to 10dp in the database, but no visibility here

<img width="716" alt="Screenshot 2025-07-10 at 2 29 02 PM" src="https://github.com/user-attachments/assets/cea2b6f8-6983-4037-a042-7b857756e153" />

**Comment by mark-prins** [comment]
@aimee-mcneil-melville 

> Should the NumberCell tooltip be rounded to a particular length? I know there are some requirements to show 10dp, however these are currently uncapped and I've seen up to 16dp

thanks - 10dp is fine

> Currency Cell: Currently this is set up to have the ellipsis and tooltip, however when the tooltip goes through currency formatting it also trims the cents to 2dp (even though precision 10 is passed in at the CurrencyCell level).

given that it has the ellipsis and tooltip, I would display the full value in the tooltip - option (c) _Tooltip to 10dp with regional currency formatting_


> There's also places that use NumericTextInputs instead of Cells. these have no default tooltip behaviour - should these also have a similar implementation?

The first screenshot of this issue is of the view stock detail page, and the number of packs uses the `NumericTextInput` - so to resolve the issue this will need to be rounded. and if rounded, ideally we'd have the tooltip showing the full value. This may be controversial, but I would have the disabled input as rounded with a tooltip, and the enabled input showing the full value which then allows users to interact correctly.

**Comment by aimee-mcneil-melville** [comment]
I think what we have here is also issues in calculation of numbers - not just the display of them. For example when issuing a prescription, only whole doses can be entered. Yet the calculated value has decimals:

<img width="439" height="155" alt="Image" src="https://github.com/user-attachments/assets/e5195fd5-310e-41c7-bf08-0c07fa94a9b8" />
<img width="617" height="391" alt="Image" src="https://github.com/user-attachments/assets/1cef9852-98c2-4d92-8b96-3fdb33e53ff1" />

**Comment by aimee-mcneil-melville** [comment]
Comments from the last ~2 days have not been resolved yet - PR #8429 is a partial fix
