### ISSUE TITLE
Seeing "Nothing here" text for internal orders on item detail window and indicators window when there are no aggregation data to show

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#7004]
## What went wrong? 😲
When there is no aggregation data from customers of the current store to show either because they are not the default supplier or there is no aggregation data to show, there is a "Nothing here" message displayed below the rest of the normal data.

Internal order item details
https://drive.google.com/file/d/1NPHQVIXmNTSHQJCf3qOIEwAXEYkKg1aB/view?usp=sharing

Internal order Indicators
https://drive.google.com/file/d/12RCvbdK9rIupf_4u99a_qL7K476y1pxo/view?usp=sharing 

## Expected behaviour 🤔
Like for Requisition no text should show (See #6147) 
## How to Reproduce 🔨

Steps to reproduce the behaviour:
Use a store that is not the default supplying store of anyone (this is set in a dropdown field in OG in the General tab of the Name window for corresponding names of stores - So no Name of store should have your store set has being their default supplier) 
Have programs setup with indicators.
1. Go to 'Replenishment > Internal order'
2. Click on 'New Internal order'
3. Choose a program that has indicators
4. When the internal order has been created, click on an item and in it's detail you will see "Nothing here"
5. Click on indicators tab then click on Regimen button
6. Again you will see the "Nothing Here" text
7. See error
 
## Your environment 🌱

- Open mSupply Version: v2.6.1RC3
- Legacy mSupply Central Server Version: v8.1.0 

- Platform: Desktop omSupply

- Database type: SQLite3

**Comment by alainsussol** [comment]
@roxy-dao 

Hi Roxy,

**Comment by andreievg** [comment]
@roxy-dao @alainsussol, i fixed here: https://github.com/msupply-foundation/civ-plugins/pull/4/commits/eb8838918d84e5c0f6ac4e8e4e08a795b4440413

New bundle here: https://github.com/msupply-foundation/civ-plugins/blob/7063-cdi-calculations-should-be-exposed-to-item-info/bundle.json

**Comment by mark-prins** [comment]
fixed in plugin repo

**Comment by alainsussol** [comment]
@mark-prins @andreievg @roxy-dao 

Is the plugin look after the indicators details aggregation box too ? Because even though the "Nothing here" message has disappear from the item detail window, I can still see it for the indicators.
